## Basic Configuration
baseurl = "https://example.com/"
languageCode = "en"

theme = "hyde-hyde"

## Site Settings
[params]
    author = "Author"
    title = "Title"
    description = "生面"
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
 
[[menu.main]]
    name = "linux"
    weight = 100
    identifier = "linux"
    url = "/linux/"

[[menu.main]]
    name = "docker"
    weight = 100
    identifier = "docker"
    url = "/docker/"

[[menu.main]]
    name = "git"
    weight = 100
    identifier = "git"
    url = "/git/"

[[menu.main]]
    name = "go"
    weight = 100
    identifier = "go"
    url = "/go/"

[[menu.main]]
    name = "win"
    weight = 100
    identifier = "win"
    url = "/win/"

[[menu.main]]
    name = "mixed"
    weight = 100
    identifier = "mixed"
    url = "/mixed/"   